name: cached_network_image_web
description: Web implementation of CachedNetworkImage
version: 1.1.1
homepage: https://github.com/Baseflow/flutter_cached_network_image

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  cached_network_image_platform_interface:
    git:
      url: git@github.com:Insight-Timer/flutter_cached_network_image.git
      ref: feature/errorListener
      path: cached_network_image_platform_interface

dev_dependencies:
  file: '>=6.1.4 <8.0.0'
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
